# Generated by Django 2.1.4 on 2018-12-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181210_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='borndate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
