# Generated by Django 2.1.4 on 2018-12-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_profile_classname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Take',
        ),
    ]
